### ISSUE TITLE
An object property to list phyloreferences in a PHYX study

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#16]
Proposed term: `has_phyloreference` (object property)
Definition: Indicates a phyloreference included in a PHYX Study (#14).
Domain: PHYX Study (#14)
Range: [`Phyloreference`](https://github.com/phyloref/phyloref-ontology/blob/6cbb9f979da44bd3ebc1c60829237317a5300f1c/phyloref.owl#L145)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L83), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L67)

Competency questions:
* Which phyloreferences are included in a PHYX study?

**Comment by hlapp** [comment]
Less trivial competency question needed.

**Comment by hlapp** [comment]
Assuming that there is a URI for the study, and if we can agree that this is a provenance relationship (for example, [`prov:wasDerivedFrom`](https://www.w3.org/TR/prov-o/#wasDerivedFrom)), then the following axiom for a phyloreference:
```
<phyloref1> rdfs:subClassOf some (prov:wasDerivedFrom value <https://doi.org/10101/phyx-study1>)
```
would enable the following DL query:
```
Phyloreference and prov:wasDerivedFrom value <https://doi.org/10101/phyx-study1>
```
Hence I don't see what need the requested property fulfills that is difficult to meet otherwise, and I therefore think this issue should be closed.

**Comment by gaurav** [comment]
Agreed! Implementing this in the phyx.js is now covered by phyloref/curation-tool#133. Closing.
