### ISSUE TITLE
A datatype property for the verbatim clade definition of a phyloreference

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#18]
Proposed term: `clade_definition`
Definition: The verbatim clade definition of a phyloreference.
Domain: [`Phyloreference`](https://github.com/phyloref/phyloref-ontology/blob/6cbb9f979da44bd3ebc1c60829237317a5300f1c/phyloref.owl#L145)
Range: [xsd:string](https://www.w3.org/TR/xmlschema11-2/#string)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L212), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L107)

Competency questions:
* What is the verbatim clade definition that this phyloreference is attempting to model?

**Comment by hlapp** [comment]
How is this different from [IAO:definition](http://www.ontobee.org/ontology/IAO?iri=http://purl.obolibrary.org/obo/IAO_0000115)?

**Comment by gaurav** [comment]
That sounds perfect for our needs! I've filed an issue to replace this term in the Curation Tool (phyloref/curation-tool#94). I'll leave this issue open to cover MIREOTing this term into our ontology.

**Comment by hlapp** [comment]
The revised Phyloref ontology in #29 proposes that indeed `IAO:definition` is to be used for this. Also, IAO:'definition source' should be used to give the citation or reference the publication.

It should be noted that `IAO:definition` is an AnnotationProperty, not a DataProperty. This seems appropriate, since there is no good use-case or competency question supporting what inference or query a reasoner should support that would requires this to be a DataProperty.

**Comment by gaurav** [comment]
Agreed! I definitely suggested too many properties as datatype properties when they should have been annotation properties instead. This will be implemented in the Curation Tool as phyloref/curation-tool#94, so I'll close it here.
