### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by hlapp** [phyloref/phyloref-ontology#22]
I notice we're missing a license / terms of reuse statement here. Any objections to choosing CC0, does anyone feel strongly about having CC-BY instead?

**Comment by ncellinese** [comment]
No objections

**Comment by gaurav** [comment]
I agree that CC-0 is the right license for the ontology!

Does the [Demonstration phylogeny for Campanulaceae](https://github.com/phyloref/phyloref-ontology/blob/d1fa6f37096f0715c04b7a7f180a7356bf786f58/campanulaceae_pruned_tree_final_no_support_value.newick) belong to us? If not, we might want to cite it rather than trying to license that under CC-0 as well.

**Comment by hlapp** [comment]
> Does the Demonstration phylogeny for Campanulaceae belong to us?
 
Yes. All your tree are belong to us. 😈
