### ISSUE TITLE
An object property for asserting that a phyloreference should resolve to a particular node in a phylogeny

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#26]
Proposed term: `has_expected_resolution`
Definition: Identifies the Node that a particular phyloreference is expected to resolve to. Additional assertations may be used to clarify who has asserted this and what evidence they used.
Domain: Phyloreference ([`phyloref:Phyloreference`](http://ontology.phyloref.org/phyloref.owl#Phyloreference))
Range: Node ([`obo:CDAO_0000140`](http://purl.obolibrary.org/obo/CDAO_0000140))

Competency questions:
* Where is this phyloreference expected to resolve on a particular phylogeny?

We currently use text-based labels for this, but plan to replace them with IRIs (phyloref/curation-tool#65).

**Comment by hlapp** [comment]
Well, if we want provenance, then we should discuss what to stick the provenance on. It's quite awkward to stick assertions (or annotations) on a property (because then properties become the subject). So perhaps this should be a class instead, and then we can use [`prov:wasGeneratedBy`](https://www.w3.org/TR/prov-o/#wasGeneratedBy), [`prov:wasDerivedFrom`](https://www.w3.org/TR/prov-o/#wasDerivedFrom) and [`prov:wasAttributedTo`](https://www.w3.org/TR/prov-o/#wasAttributedTo) to track who or what process posited the resolution.

**Comment by hlapp** [comment]
In the revised Phyloref model proposed in #29, this is to be expressed with the following pattern:

```
rdf:type (obi:is_specified_output_of some 
    (obi:prediction and (obi:has_specified_input some <Phyloreference>))
```
where `<Phyloreference>` is the class for which the node instance is expected as the resolution.

In an example:
```
# Individual: :CLADO_00000062_node22 (Alligatoridae)
ClassAssertion(
    ObjectSomeValuesFrom(
        obo:OBI_0000312 ObjectIntersectionOf(
            obo:OBI_0302910 ObjectSomeValuesFrom(obo:OBI_0000293 :CLADO_00000010)))
    :CLADO_00000062_node22)
```

**Comment by gaurav** [comment]
Sounds good! This will be implemented in phyloref/phyx.js#4.
