### ISSUE TITLE
An object property for referencing taxonomic units from specifiers

### ISSUE THREAD

**Issue by gaurav** [phyloref/phyloref-ontology#6]
Proposed term: [`cdao:represents_TU`](http://purl.obolibrary.org/obo/CDAO_0000187) (object property)
Definition: A taxonomic unit referenced by an entity that can be identified to a taxon. This entity might reference multiple taxonomic units, any of which can be matched.
Domain: Specifier (#5) or Node ([CDAO_0000140](http://purl.obolibrary.org/obo/CDAO_0000140))
Range: TU ([obo:CDAO_0000138](http://purl.obolibrary.org/obo/CDAO_0000138) or #10)
See also: [scratch ontology](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/ontologies/phyloref_testcase.owl#L182), [PHYX context](https://github.com/phyloref/clade-ontology/blob/ddf7c53b60cc4a53c21e7d4b2ceb09a17be66f44/testcase2owl/paper-context.json#L218)

Competency questions:
* Which taxonomic units does a particular specifier refer to?
* Which taxonomic units are contained in a particular specifier?
* Which taxonomic units is a particular specifier composed of?

**Comment by hlapp** [comment]
See [comment on #8](https://github.com/phyloref/phyloref-ontology/issues/8#issuecomment-386127992) re: supporting competency question(s). Isn't there `references_TU` already in CDAO, so that we could simply import that term?

**Comment by gaurav** [comment]
I've added a competency question -- let me know what you think! We could use [`cdao:represents_TU`](http://purl.obolibrary.org/obo/CDAO_0000187) instead, but that term has an explicit domain of [`cdao:Node`](http://purl.obolibrary.org/obo/CDAO_0000140) -- so using it would imply that a Specifier is also a Node, which doesn't make sense to me. Could we somehow include it without including that implication?

**Comment by hlapp** [comment]
> I've added a competency question -- let me know what you think!

Good start, but it doesn't necessarily show (yet?) why we need this property. For example, wouldn't we be able to get the answer by simply querying which objects of type `cdao:TU` are linked to the specifier subject, regardless of property?
 
> We could use cdao:represents_TU instead, but that term has an explicit domain of cdao:Node -- so using it would imply that a Specifier is also a Node, which doesn't make sense to me.

Right. I think that's an issue to be reported to the CDAO tracker.

Are you saying that if that were fixed in CDAO, there would be no hindrance to reusing the CDAO property?

> Could we somehow include it without including that implication?

Yes, at least temporarily. I think it may not be viable anyway to import CDAO as a whole as it's now (because it drives up the required expressivity profile), so we'll probably at least in the interim end up extracting a subset of axioms from CDAO.

**Comment by gaurav** [comment]
> Good start, but it doesn't necessarily show (yet?) why we need this property. For example, wouldn't we be able to get the answer by simply querying which objects of type `cdao:TU` are linked to the specifier subject, regardless of property?

I'm not sure I understand what you mean. If this isn't the property used to link Specifiers to `cdao:TU`, then what is? Or do you mean that my competency question should be more specific? I've added two new competency questions to the issue that might help with this -- let me know what you think!

>> We could use cdao:represents_TU instead, but that term has an explicit domain of cdao:Node -- so using it would imply that a Specifier is also a Node, which doesn't make sense to me.
> Right. I think that's an issue to be reported to the CDAO tracker.
>
> Are you saying that if that were fixed in CDAO, there would be no hindrance to reusing the CDAO property?

Actually, yes. I think node identification and specifier identification are similar enough that we could refer to them in the same way.

>> Could we somehow include it without including that implication?
> Yes, at least temporarily. I think it may not be viable anyway to import CDAO as a whole as it's now (because it drives up the required expressivity profile), so we'll probably at least in the interim end up extracting a subset of axioms from CDAO.

Sounds good! I've modified this issue to incorporate `cdao:represents_TU` rather than creating our own term. If we do this and it works successfully, we could open an issue with them to broaden the range of `cdao:represents_TU`.

**Comment by hlapp** [comment]
In light of the conclusion from recent discussions that at least for purposes of phylogenetic clade definitions there is no discernible difference between a specifier and a referent to a taxon concept, I would argue the concern about the domain constraint of `cdao:represents_TU` is no longer pertinent, since there is no good reason not to link directly from a node to the `cdao:TU` that it represents. Therefore this should be closed.

**Comment by gaurav** [comment]
Agreed! Closing.
